# Site settings
title: Liangrong 的角落
email: your-email@example.com
description: >-
  记录思考，分享成长
baseurl: "/my-blog"
url: ""

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor
  - .sass-cache
  - .jekyll-cache
  - .jekyll-metadata
  - README.md

# Author settings
author:
  name: Liangrong
  email: your-email@example.com

# Social links (optional)
minima:
  social_links:
    github: liangrong3208

# Pagination (optional)
paginate: 5
paginate_path: "/page:num/"
